### ISSUE TITLE
Turn on support for big structs

### ISSUE THREAD

**Issue by Emilgardis** [museun/json_to_rust#5]
7026e51e29e53a6d02d3265f14aafeb92afa60d2 removed this feature. Having this again would be great, as currently objects get converted to `HashMap<String, serde_json::Value>`, always. I think a good solution would be to just walk over again. I don't think size of struct should matter, if it does, one could always add a `#[serde(flatten)] other: HashMap<String, serde_json::Value>` to the struct

**Comment by museun** [comment]
I've added back in the re-walking of the tree, but this time with a bit of heuristics on whether to flatten or re-walk.

try out bfb796ea446bd6f51c6c53f923790793e30a1541

**Comment by Emilgardis** [comment]
Works nicely.

**Comment by museun** [comment]
I pushed v0.2.0, I think its usable/correct enough that I can publish it to crates.io.
